### ISSUE TITLE
Why have you commented all the code?

### ISSUE THREAD

**Issue by gaal1le0** [jesus-cano-ortega/traffic-light-state#1]
https://github.com/jesus-cano-ortega/traffic-light-state/blob/4874d71842bc758b6c108703cfde91b541b7d149/src/js/index.js#L1

Please keep in mind that commented all the code which are obvious is one of the biggest mistake you can get while you are learning. Please only comment code which can confuse to someone who are working with you. Is obvious that the following sentence import a component so you don't need to comment it.

```js
import Home from '../Home.jsx'
```

Please remove all the unnecessary comments from your project and close the issues once you have finished. Later please deliver the assignment again via BreathCode.

**Comment by jesus-cano-ortega** [comment]
Unnecessary comments removed. I proceed to close the issue.

Thanks for your feedback, Tech Lead.

**Comment by gaal1le0** [comment]
I hope you have taken this comments from a constructive point of view, I am only trying to make you a great developer.
