### ISSUE TITLE
Why this component is called `Home`?

### ISSUE THREAD

**Issue by gaal1le0** [jesus-cano-ortega/traffic-light-state#2]
https://github.com/jesus-cano-ortega/traffic-light-state/blob/4874d71842bc758b6c108703cfde91b541b7d149/src/js/component/home.jsx#L4

I really don't understand why this component (which definition is a `TrafficLight`) is called `Home`. I know you think that "naming" isn't important but you are really wrong. Naming is one of the most important thing to keep a project safe, think in the future not only in accomplish the task. 

All of you are focus on deliver the assignment ASAP not on creating the best approach to satisfy the customer requirements.

**Comment by jesus-cano-ortega** [comment]
Name of the modified component. I proceed to close the issue.

Thanks for your feedback, Tech Lead.
